mysql:
  host: "127.0.0.1"
  port: 3306
  user: "gosentinel"
  password: "gosentinel"
  dbname: "gosentinel"
  charset: "utf8mb4"

logging:
  level: "debug"
  max_age_days: 7

server:
  http_address: "0.0.0.0"
  http_port: 80
  app_name: "GoSentinel"
  agent_port: 9999

jwt:
  secret: "SUkYUQo62eeGuULE8apNaZMLZGPPfMdI"
  expiration_hours: 8